# Generated by Django 2.0.3 on 2019-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeReport',
            fields=[
                ('report_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=32)),
                ('upload_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('employee_id', models.CharField(max_length=16)),
                ('job_group', models.CharField(max_length=32)),
                ('pay_period', models.DateField()),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('date', 'employee_id')},
        ),
    ]
